// Generated by gencpp from file sick_scan/ECRChangeArrSrvRequest.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_ECRCHANGEARRSRVREQUEST_H
#define SICK_SCAN_MESSAGE_ECRCHANGEARRSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sick_scan
{
template <class ContainerAllocator>
struct ECRChangeArrSrvRequest_
{
  typedef ECRChangeArrSrvRequest_<ContainerAllocator> Type;

  ECRChangeArrSrvRequest_()
    : active(false)  {
    }
  ECRChangeArrSrvRequest_(const ContainerAllocator& _alloc)
    : active(false)  {
  (void)_alloc;
    }



   typedef uint8_t _active_type;
  _active_type active;





  typedef boost::shared_ptr< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ECRChangeArrSrvRequest_

typedef ::sick_scan::ECRChangeArrSrvRequest_<std::allocator<void> > ECRChangeArrSrvRequest;

typedef boost::shared_ptr< ::sick_scan::ECRChangeArrSrvRequest > ECRChangeArrSrvRequestPtr;
typedef boost::shared_ptr< ::sick_scan::ECRChangeArrSrvRequest const> ECRChangeArrSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sick_scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'sick_scan': ['/home/collabai/ros_catkin_ws/src/sick_scan/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c5cfb0a2565df41de6873994aee57d2";
  }

  static const char* value(const ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c5cfb0a2565df41ULL;
  static const uint64_t static_value2 = 0xde6873994aee57d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sick_scan/ECRChangeArrSrvRequest";
  }

  static const char* value(const ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"bool active\n"
"\n"
;
  }

  static const char* value(const ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ECRChangeArrSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sick_scan::ECRChangeArrSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SICK_SCAN_MESSAGE_ECRCHANGEARRSRVREQUEST_H
